GET http://localhost:3004/players/
###

GET http://localhost:3004/players/2
###


PUT http://localhost:3004/players/10/
Content-Type: application/json

{
  "playerName": "Raju"
}
###

GET http://localhost:3004/matches/18/
###

GET http://localhost:3004/players/1/matches
###

GET http://localhost:3004/matches/2/players
###


GET http://localhost:3004/players/1/playerScores

